version: "3.9"
services:
  urlshortener:
    build:
      context: src/urlshortener
      args:
        GIT_TAG: dev
    depends_on:
      - redis
    ports:
      - "8080:8080"
  redis:
    image: "redis:6.2.6"
