apiVersion: k3d.io/v1alpha3
kind: Simple
name: dev
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: k3d-registry.localhost
    host: "127.0.0.1"
    hostPort: "50000"