# For example purposes only.
# Secrets should be managed by a secrets management system such as Vault.
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
stringData:
  password: test-redis-password
