apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "urlshortener.fullname" . }}
  labels:
  {{- include "urlshortener.labels" . | nindent 4 }}
  {{- include "urlshortener.selectorLabels" . | nindent 4 }}
data:
  {{ .Values.config.configMap.subPath }}: |
    {{- toYaml .Values.config.configMap.data | nindent 4 }}
