apiVersion: v1
kind: Secret
metadata:
  name: {{ include "urlshortener.fullname" . }}
  labels:
  {{- include "urlshortener.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range .Values.config.secrets }}
  {{ .key }}: {{ toYaml .data | b64enc }}
  {{- end}}
