apiVersion: v1
kind: Service
metadata:
  name: {{ include "urlshortener.fullname" . }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
  labels:
  {{- include "urlshortener.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
  {{- include "urlshortener.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol | default "TCP" }}
      {{- if .targetPort }}
      targetPort: {{ .targetPort }}
      {{- end }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
  {{- end -}}
  {{- end -}}
