// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package oapi

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// ShortenedURL defines model for ShortenedURL.
type ShortenedURL struct {
	ShortUrl string `json:"shortUrl"`
}

// URL defines model for URL.
type URL struct {
	ExpireAt *int64 `json:"expireAt,omitempty"`
	Url      string `json:"url"`
}

// Version defines model for Version.
type Version struct {
	Revision string `json:"revision"`
	Version  string `json:"version"`
}

// BadRequest defines model for BadRequest.
type BadRequest Error

// NotFound defines model for NotFound.
type NotFound Error

// PostV1UrlJSONBody defines parameters for PostV1Url.
type PostV1UrlJSONBody URL

// PostV1UrlJSONRequestBody defines body for PostV1Url for application/json ContentType.
type PostV1UrlJSONRequestBody PostV1UrlJSONBody

