kind: ConfigMap
apiVersion: v1
metadata:
  name: urlshortener-cm
data:
  config.yaml: |
    server:
      address: ":8080"
    logger:
      development: false
    redis:
      retries: 6
      minRetryBackoff: 1000
      maxRetryBackoff: 32000
