kind: ConfigMap
apiVersion: v1
metadata:
  name: urlshortener-cm
data:
  config.yaml: |
    server:
      address: ":8080"
      delaySigterm: 5
    logger:
      development: false
    redis:
      host: "redis-svc"
      port: "6379"
      retries: 6
      minRetryBackoff: 1000
      maxRetryBackoff: 32000
