apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortener-deployment
  labels:
    app: urlshortener
spec:
  replicas: 8
  selector:
    matchLabels:
      app: urlshortener
  template:
    metadata:
      labels:
        app: urlshortener
    spec:
      containers:
        - name: urlshortener
          image: k3d-registry.localhost:50000/urlshortener:latest
          ports:
            - name: service-port
              containerPort: 8080
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 15
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/nap", "5" ]
          resources:
            requests:
              memory: 14Mi
              cpu: 240m
            limits:
              memory: 28Mi
          volumeMounts:
            - name: config
              mountPath: "/etc/app/"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: urlshortener-config
