apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortener-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: urlshortener
  template:
    metadata:
      labels:
        app: urlshortener
    spec:
      containers:
        - name: urlshortener
          image: k3d-registry.localhost:50000/urlshortener:latest
          ports:
            - name: service-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: service-port
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /livez
              port: service-port
            initialDelaySeconds: 15
          resources:
            requests:
              memory: 14Mi
              cpu: 240m
            limits:
              memory: 28Mi
          volumeMounts:
            - name: config
              mountPath: "/etc/app/"
              readOnly: true
      volumes:
        - name: config
          projected:
            sources:
              - secret:
                  name: urlshortener-secret
                  items:
                    - key: redis.yaml
                      path: secrets/redis.yaml
              - configMap:
                  name: urlshortener-cm
                  items:
                    - key: config.yaml
                      path: config.yaml
