version: "3.9"
services:
  urlshortener:
    build:
      context: ../../src/urlshortener
      args:
        GIT_TAG: dev
    volumes:
      - ./config/urlshortener/config.yaml:/etc/app/config.yaml
      - ./config/urlshortener/redis.yaml:/etc/app/secrets/redis.yaml
    depends_on:
      - redis
    ports:
      - "8080:8080"
  redis:
    image: "redis:6.2.6"
    command: redis-server --requirepass test-redis-password
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
