// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Creates a new shortened URL
	// (POST /url)
	PostUrl(ctx echo.Context) error
	// Redirects to URL that was shortened
	// (GET /url/{shortened})
	GetUrlShortened(ctx echo.Context, shortened string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostUrl converts echo context to params.
func (w *ServerInterfaceWrapper) PostUrl(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostUrl(ctx)
	return err
}

// GetUrlShortened converts echo context to params.
func (w *ServerInterfaceWrapper) GetUrlShortened(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "shortened" -------------
	var shortened string

	err = runtime.BindStyledParameterWithLocation("simple", false, "shortened", runtime.ParamLocationPath, ctx.Param("shortened"), &shortened)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter shortened: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUrlShortened(ctx, shortened)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/url", wrapper.PostUrl)
	router.GET(baseURL+"/url/:shortened", wrapper.GetUrlShortened)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xU3WrbTBB9lWW+76IFYSk/tKC7pLQlkKbBraEQcrHRju0N1u5mdpTEGL17mZWtyKna",
	"QAm9knZndObMmaPZQOXr4B06jlBugDAG7yKmw6k2U7xrMLKcKu8YXXrVIaxspdl6l99G7+QuVkustbz9",
	"TziHEv7Ln6DzLhrzj0SeoG3bDAzGimwQECjh+xJVDFjZuUWjqCurHnRUN9qs1mruqdbMaKDN4MLzJ984",
	"8+9pRd9QhYmX86zmiYV8tkWSQh1YuQF81HVYYcfSIJQwc/auQYWSodJdBjXGqBcSTR+q3bnNIJAPSGy7",
	"cXQYG+B1kOzIZN1C0nqEX2JtBiKlJTRQXsGzitfZLt/f3GLFgvVt6YnRoZlNzwVwn0KU6IxW8t5NBEpo",
	"yEL2QuX+w7Gao6XwMVjCE94rZR2/O34qZh3jAkkwmr8g1YzykSzr5j7JaXmV5jY9V3GrDKmTyzPI4B4p",
	"diYpJgeTQkj4gE4HCyUcTYpJARkEzcvUTr4lGHz3N0mryalnBkq49DGp0/HDyKferF/N3aLviLelKfbq",
	"BvvWjHqwvFTaKZ+S9EqlMazV7OLsh2JbY2RdBxjqyNRgEnawOQ6Lg1djv+fIkTb6uJKGKkK93RLHRfE7",
	"7J5sPthx6Tdu6lrTGkr4kICi0srhw0ChjkWWBppv+vtWSi1wZLafUUbbs0ymIF0jI0UorzZ/agfEilAm",
	"G0EGTtfJzgOs/TlkA01r/XiObsFLKN9nUFs3OD3/L66fze+oOJTHPrMpGktYMRqxTdJBRD5+WeR+X+9L",
	"vAOMWzzFS93t/KcO08Aj0v24Wl93Pu1S1CCaKZwsJuqLtk69CeRNU8n1220qbHcG5PcH0F63PwMAAP//",
	"7ULumwoHAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

