// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package api

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ShortenedURL defines model for ShortenedURL.
type ShortenedURL struct {
	ShortUrl string `json:"shortUrl"`
}

// URL defines model for URL.
type URL struct {
	ExpireAt *int64 `json:"expireAt,omitempty"`
	Url      string `json:"url"`
}

// BadRequest defines model for BadRequest.
type BadRequest Error

// NotFound defines model for NotFound.
type NotFound Error

// PostUrlJSONBody defines parameters for PostUrl.
type PostUrlJSONBody URL

// PostUrlJSONRequestBody defines body for PostUrl for application/json ContentType.
type PostUrlJSONRequestBody PostUrlJSONBody

